version: "3"

services:
  keyrace:
    image: keyrace
    build: .
    depends_on:
      - postgres
    networks:
      keyrace:
        ipv4_address: 10.5.0.2
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    networks:
      keyrace:
        ipv4_address: 10.5.0.3
    ports:
      - "5432:5432"

networks:
  keyrace:
    external: true