version: "3"

services:
  keyrace:
    image: keyrace
    build: .
    depends_on:
      - postgres
    network_mode: "host"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    network_mode: "host"